name: Prod CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Deploy to Production
      env:
        API_KEY: ${{ secrets.GCP_API_KEY }}
      run: |
        echo "Deploying to Production..."
        # Insert deployment script here (e.g. gcloud run deploy)
